### ISSUE TITLE
Docs don't provide enough motivation

### ISSUE THREAD

**Issue by tseaver** [Pylons/plaster#11]
The only description of "what does this do" is the first line:

> plaster is a loader interface around arbitrary config file formats. 

There should be some description about what those formats are (INI, plus what?), preferably with examples showing each supported type with equivalent configuration.

**Comment by mmerickel** [comment]
Well the only impl right now is plaster_pastedeploy but we could add a link to it.

**Comment by mmerickel** [comment]
I've updated the docs with a brief intro and a known loaders section. Let me know what you think.

**Comment by tseaver** [comment]
I added a couple of line comments to that commit.

Maybe we should arrange to have at least one more loader available by default?  E.g., what about one which does only stdlib logging configuration?

**Comment by mmerickel** [comment]
> Maybe we should arrange to have at least one more loader available by default? E.g., what about one which does only stdlib logging configuration?

I think this is probably a good idea for the convenience apis (`plaster.get_settings`, `plaster.get_sections` and `plaster.setup_logging`). They could simply catch `LoaderNotFound` and return `{}`, `[]` and call `basicConfig` respectively.

**Comment by tseaver** [comment]
Why is `plaster.setup_logging` a thing?  Shouldn't that be done by whatever loader is configured?

**Comment by mmerickel** [comment]
Yeah they are thin wrappers around the loader to accommodate simple use-cases. All 3 of them are unnecessary if you want to just call `plaster.get_loader()` directly but in general that's only necessary if you want a handle to the actual loader object (usually only when it implements extra methods defined by the requested protocol - such as `loader.get_wsgi_app()`).

**Comment by tseaver** [comment]
But `loader.setup_logging()` feels exactly parallell to `loader.get_wsgi_app()`.

**Comment by mmerickel** [comment]
I concluded that the 3 methods (``get_sections``, ``get_settings`` and ``setup_logging``) were the base functionality required by any arbitrary application and so there are convenience wrappers for them. The protocol system is for advanced functionality such as wsgi-specific methods.

**Comment by mmerickel** [comment]
I think I've decided that having the methods do something by default even if a loader is not found is a bad idea because it will hide the fact that a file was not found. I'd rather the application decide what to do there. I'm talking explicitly about adding this code:

```python
def setup_logging(config_uri, defaults):
    try:
        loader = get_loader(config_uri)
    except LoaderNotFound as ex:
        logging.basicConfig()
        log.warn(ex.message)
        return
    return loader.setup_logging(defaults)
```

**Comment by mmerickel** [comment]
Please keep the questions coming but I'm going to close the issue for now as I've improved the docs a lot based on your feedback I think.
