### ISSUE TITLE
update parse_uri to use 'file+ext' as the scheme if 'ext' was pulled from the file extension

### ISSUE THREAD

**Issue by mmerickel** [Pylons/plaster#15]
Currently if `parse_uri('development.ini')` is used, the protocol will be 'ini' but this scheme can be considered a little ambiguous with `ini://foo`. It would be clearer if, when the scheme is constructed from a file extension, it began with `file+` which would also be usable by users to know that the path came from a file on disk.

This change would likely be backward incompatible and require a change to the one known loader, plaster_pastedeploy to define support for `file+ini` instead of just `ini`.

**Comment by mmerickel** [comment]
@huntcsg did this go anywhere? I'm happy to take it but don't want to step on your toes.

**Comment by mmerickel** [comment]
At the end of the day I'm fine with deciding that this shouldn't be changed or coming up with an alternate solution. As we discussed the other day the primary motivator here is to disambiguate `foo.egg` and `egg:foo` by forcing the former scheme to be something like `file+egg:foo`. This way loaders would not be forced to support the file extension syntax... no loader would be found for `file+egg` requiring the user to use `egg:foo` instead.

I'm wondering if we invert the scheme lookup to be "most specific first" instead of "least specific first" things would be more clear. See below:

## Current situation

### plaster_pastedeploy schemes

- `ini`
- `ini+pastedeploy`
- `egg`
- `egg+pastedeploy`

### All possible URIs

- `development.ini` -> `ini:development.ini`
- `ini:development.ini`
- `ini+plaster_pastedeploy:development.ini` **absolute lookup**
- `development.ini+pastedeploy` -> `ini+pastedeploy:development.ini+pastedeploy`
- `ini+pastedeploy:development.ini`
- `development.ini+pastedeploy+plaster_pastedeploy` -> `ini+pastedeploy+plaster_pastedeploy:development.ini+pastedeploy+plaster_pastedeploy` **absolute lookup**
- `ini+pastedeploy+plaster_pastedeploy:development.ini` **absolute lookup**
- `development.egg` -> `egg:development.egg`
- `egg:myapp`
- `egg+plaster_pastedeploy:myapp` **absolute lookup**
- `development.egg+plaster_pastedeploy` -> `egg+plaster_pastedeploy:development.egg+plaster_pastedeploy`
- `egg+pastedeploy:myapp`
- `egg+pastedeploy+plaster_pastedeploy:myapp`

## Suggested change

### plaster_pastedeploy schemes

- `ini`
- `file+ini`
- `pastedeploy+ini`
- `egg`
- `pastedeploy+egg`

### All possible URIs

- `ini:development.ini`
- `plaster_pastedeploy+ini:development.ini` **absolute lookup**
- `development.ini` -> `file+ini:development.ini`
- `file+ini:development.ini`
- `plaster_pastedeploy+file+ini:development.ini` **absolute lookup**
- `pastedeploy+ini:development.ini`
- `plaster_pastedeploy+pastedeploy+ini:development.ini` **absolute lookup**
- `egg:myapp`
- `plaster_pastedeploy+egg:myapp` **absolute lookup**
- `pastedeploy+egg:myapp`
- `plaster_pastedeploy+pastedeploy+egg:myapp` **absolute lookup**

If you stare at this until your eyes bleed I think you'll agree that the second approach yields more approachable URIs. The only issue I can't rationalize very easily in the second approach is whether it's a good idea to reverse the order of items in the lookup but I think it's an improvement.

**Comment by digitalresistor** [comment]
I am a fan of the second more so than the first. Seems like there is less possible confusion regarding what loader is used and when.

```
development.ini+pastedeploy
```

This being turned into  `ini+pastedeploy:development.ini+pastedeploy`, I am a huge :-1:
