### ISSUE TITLE
Feature Request: Allow loading files without an extension

### ISSUE THREAD

**Issue by NickBeeuwsaert** [Pylons/plaster#21]
Disclaimer: this might be out of scope for this project, so feel free to close if it is.

There are a few tools that use config files without an extension to specify configuration. Off the top of my head, there is Pipfile, Dockerfile, Makefile, Gemfile, and Jakefile.

It would be useful, if when parse_uri is passed a filename without an extension, we could get something back like `PlasterURL('file+dockerfile://Dockerfile')` (My specific use case is a Dockerfile, but Pipfile is probably more relevant to the python ecosystem)

There are some edge cases where you would pass one of these files with an extension, for instance when a project has different makefiles for different platform, or a dockerfile for different deployments, and I'm not quite sure how to handle that besides manually setting a scheme before calling parse_uri

**Comment by digitalresistor** [comment]
Plaster already supports explicitly passing in the file type, I think it is out of scope for the project to try and guess the filetype for the bare files like you are asking for here.
