### ISSUE TITLE
With plaster 1.1,  ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by rsgmon** [Pylons/plaster#26]
## Get Support
To get help or technical support, see [Get Support](https://pylonsproject.org/community-support.html).

## Bug Report

Please [search the issue tracker](https://github.com/Pylons/plaster/issues) for similar issues before submitting a new issue.

**Describe the bug**
When trying to run pshell or pserve get `ModuleNotFoundError: No module named 'importlib_metadata'`

**To Reproduce**
pshell myinifile.ini or pserve myinifile.ini

**Expected behavior**
pyramid pshell starts or pyramid pserve runs

**TraceBack**
`Traceback (most recent call last):
  File "/usr/local/VMS/docker/py37vms/lib/python3.7/site-packages/plaster/loaders.py", line 2, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (/usr/local/lib/python3.7/importlib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/VMS/docker/py37vms/bin/pserve", line 5, in <module>
    from pyramid.scripts.pserve import main
  File "/usr/local/VMS/docker/py37vms/lib/python3.7/site-packages/pyramid/scripts/pserve.py", line 22, in <module>
    from pyramid.scripts.common import get_config_loader, parse_vars
  File "/usr/local/VMS/docker/py37vms/lib/python3.7/site-packages/pyramid/scripts/common.py", line 1, in <module>
    import plaster
  File "/usr/local/VMS/docker/py37vms/lib/python3.7/site-packages/plaster/__init__.py", line 6, in <module>
    from .loaders import find_loaders, get_loader, get_sections, get_settings, setup_logging
  File "/usr/local/VMS/docker/py37vms/lib/python3.7/site-packages/plaster/loaders.py", line 4, in <module>
    import importlib_metadata as metadata
ModuleNotFoundError: No module named 'importlib_metadata'`

**Comment by mmerickel** [comment]
Ok so this issue should only occur with Python 3.7 because it requires importlib_metadata to get installed. That being said, I'm unable to repro this issue. What version of pip did you use to install plaster? Is it insanely old?

I tried the following on Python 3.7.15 and did not observe a problem.

```
$ docker run --rm -it python:3.7 /bin/bash
$ apt update && apt install -y vim
$ python3 -m venv env
$ env/bin/pip install cookiecutter
$ env/bin/cookiecutter gh:Pylons/pyramid-cookiecutter-starter --checkout 2.0-branch
$ cd pyramid_scaffold
$ python3 -m venv env
$ env/bin/pip install -U pip setuptools
$ # <snip> edit development.ini to change localhost to `*`
$ env/bin/pserve development.ini
```

When invoking pserve at the end I would expect to see the same issue you are reporting but I do not because importlib-metadata was installed successfully.

**Comment by mmerickel** [comment]
There's a bunch of dependencies that should install importlib-metadata and for it to not be there indicates maybe a pretty old pip that doesn't understand the package metadata to install dependencies based on python version.

**Comment by rsgmon** [comment]
pip 20.0.2 and python 3.7.6

**Comment by mmerickel** [comment]
Are you able to run through my repro steps on your system... not the docker stuff, but installing the starter cookiecutter, and seeing if that also fails?

**Comment by rsgmon** [comment]
I ran through all repro steps, including the original ones above, and variations like only upgrading setuptools, only upgrading pip and none failed.

**Comment by rsgmon** [comment]
After upgrading pip the problem was solved. Thanks for your help.

**Comment by mmerickel** [comment]
I still can't repro with pip 20.0.2 but yeah we'll reopen if we can pin down what happened better. Thanks!
